name: Deploy latest site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: copy-files-to-server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: "deployer"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "index.html"
          target: "/var/www/luveshsadhwani.com"
